# Configuration for Exercise2.1

# Path settings
assets_dir: assets
models_dir: models
outputs_dir: outputs
sprites_data: data/sprites.npy

# Training settings
seed: 2929
batch_size: 8
num_samples: 40000
img_size: 16
T: 500
beta_start: 0.0001
beta_end: 0.02
input_channels: 3
channels: 32
time_dim: 256
lr: 0.001
num_epochs: 30
experiment_name: ddpm

# Visualization
show_images: true
