run_name: ddim_guidance_10_0
input_image: "../assets/group_photo.jpeg"
input_image_prompt: "two young men sitting at a desk in an office"
edit_prompt: "two young men sitting at a desk in an office wearing sunglasses"
num_steps: 100
start_step: 25
guidance_scale: 10.0
